### ISSUE TITLE
Spam detectado

### ISSUE THREAD

**Issue by gamees** [Cassianokunsch/instagram-prize-draw#3]
Sempre tento rodar o bot mas toda vez faz 7 a 9 comentarios e diz q foi detectado spam e pede pra eu esperar horas (as vezes espero 10 horas e nada de voltar) oq posso fazer pra arrumar isso ?

**Comment by Cassianokunsch** [comment]
Então cada conta tem sua particularidade, talvez os caras que você está marcando não seguem você e acho que o Instagram não gosta desse tipo de coisa. Dê preferência em marcar quem te segue.
